---
- hosts: demogroup
  tasks:
  - name: Installing httpd
    yum:
      name: httpd
      state: present
  - name: starting httpd
    service:
      name: httpd
      state: started
  - name: example copying file with owner and permissions
    copy:
      src: /etc/ansible/index.html
      dest: /var/www/html/index.html
